services:
  nginx:
    platform: linux/arm64
    ports:
      - "8080:80"
  app:
    platform: linux/arm64
    build:
      context: ./app
      dockerfile: Dockerfile.alpine
    ports:
      - "8000:8000"




